#ifndef VERSION_H
#define VERSION_H

#define VERSION_NAME   "CloverGit"
#define VERSION_MAJOR  0
#define VERSION_MINOR  1
#define VERSION_BUILD  0
#define VERSION_FLAVOR ""

#define VERSION_FULL VERSION_NAME "-" #VERSION_MAJOR "." #VERSION_MINOR "." #VERSION_BUILD VERSION_FLASVOR

#endif // VERSION_H
